### ISSUE TITLE
traceback

### ISSUE THREAD

**Issue by potuz** [JacobDomagala/StaticAnalysis#19]
With the last change to support different missing packages, I get this trace

```
+ python3 /run_static_analysis.py -cc cppcheck.txt -ct clang_tidy.txt
Traceback (most recent call last):
Changed files 32
  File "/run_static_analysis.py", line 231, in <module>
    files_changed_in_pr_in = setup_changed_files()
  File "/run_static_analysis.py", line 84, in setup_changed_files
    lines_changed_for_file = get_lines_changed_from_patch(file.patch)
  File "/run_static_analysis.py", line 60, in get_lines_changed_from_patch
    idx_end = line[idx_beg:].index(",")
ValueError: substring not found
```

**Comment by potuz** [comment]
Ok it seems that `cppcheck` cannot be run with `suppressions-list` , as soon as I took that file out the checker works.

**Comment by potuz** [comment]
I take this back, this same trace appears and goes on the same pull request with very minor updates.

**Comment by JacobDomagala** [comment]
Thanks @potuz! Should be fixed now
